token:
  expiration_time: 86400000
  secret: '{cipher}AYAtbBuDdUKnvkdh/k2SUcV2WePZv9EKJJfmlhtrrApcrTNNPgUG96T0jXBqa5A401HLJpWJpEmjtURORlvOVZ82vVbtdmZAT9PmMoeM32hk6XjGBj7oyWAyey3k5BYvnqPVtAZTpuJlHWf8S1dqDZyEphqd09s6QJBSJS5lf9NwTn6ZwzkPQgpjTSo4gGYX+HiYEi7CSiocIPHZ9OEmA3PG2PrJLNAzDN18P6kKqkcYzDxhIFDLHQa6U8pVsXbQ9osWNt3HJMZCjhQPNbJp0nuM7ahg3bF0B9IRUyoCk+ae/y06S2UV5aTULihH7rS9EKq9CZwh7oTi4vmMMswK9WUr/mVzG9h8K1Gew3o0vB0pclkSLm2N2rgJsmoNgvP+UTKWyeMXJosrBED/BTLYQ6fWSx/Z2ps0w9aybxYauUPgPh4IwIJ69ynvca19zoYy/SLRDbBXTRgAn7GHTUNq07MvlzQYEnT2rEatFzsuyAStugzwPikqJBCuf3PBNq4gUPx/2E6fdOhEr58VQEkVr0qG/RP80Qn2fv/yRgkXoj+Qi6f/c+XiJc3TzIVYbslL5i8='

gateway:
  ip: 172.18.0.5