spring:
  datasource:
    # driver-class-name: org.mariadb.jdbc.Driver
    # password: '{cipher}AYBB9y1nBmFzZ5791TfOzRExv9K+Oa11i6F9ShvIcWnA9oQSFz0S6zSozJqgDv3eWd7/KMs7FbUMnKO87sb4/Lzes8Q8PC5ryjmIE5efQ7Fis1RZOX6/gVzetC2uhjTcn0wz90MyWCxYDL1SmtopeqNvrfIVw9Qb88Y3J3yBZjr8IXxASw/QSG+UUg5GMk8zi075M5YmOm5noD8msb8J7ym++piUnpxFA16DpF2j7IkeJZSEvt0aD8CtbnsN396m8KgeZbEGMV9oaBxUzAZ1UFa254aLuLukP9In8V/hwDJiiAUPBY9vmWg0G3kVSQQ7T785Tr4RqosPv4CvmdvI6IRhhlefbE81p2hN2EkTmXWF3j0DIQrzE6FjWcLl9u9QEMAOHsQLpcoAZADZ4F5x6ngd7zSbz80KTdOF2umKr+SavtxN2z30uww2gIW7rID4OGXZkWQtClPj0kb68tNoSahZW/nvhw/W9OKUWoE4Oyc27wGJyNKCz6ulpKpx2LRg9avuz2gnU5NSncNhAkKB0Mv7H+daaqiw8LRyrIZlqixKZA=='
    # url: jdbc:mariadb://localhost:3307/mydb
    # username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '{cipher}AYBB9y1nBmFzZ5791TfOzRExv9K+Oa11i6F9ShvIcWnA9oQSFz0S6zSozJqgDv3eWd7/KMs7FbUMnKO87sb4/Lzes8Q8PC5ryjmIE5efQ7Fis1RZOX6/gVzetC2uhjTcn0wz90MyWCxYDL1SmtopeqNvrfIVw9Qb88Y3J3yBZjr8IXxASw/QSG+UUg5GMk8zi075M5YmOm5noD8msb8J7ym++piUnpxFA16DpF2j7IkeJZSEvt0aD8CtbnsN396m8KgeZbEGMV9oaBxUzAZ1UFa254aLuLukP9In8V/hwDJiiAUPBY9vmWg0G3kVSQQ7T785Tr4RqosPv4CvmdvI6IRhhlefbE81p2hN2EkTmXWF3j0DIQrzE6FjWcLl9u9QEMAOHsQLpcoAZADZ4F5x6ngd7zSbz80KTdOF2umKr+SavtxN2z30uww2gIW7rID4OGXZkWQtClPj0kb68tNoSahZW/nvhw/W9OKUWoE4Oyc27wGJyNKCz6ulpKpx2LRg9avuz2gnU5NSncNhAkKB0Mv7H+daaqiw8LRyrIZlqixKZA=='
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


token:
  expiration_time: 86400000
  secret: '{cipher}AYAtbBuDdUKnvkdh/k2SUcV2WePZv9EKJJfmlhtrrApcrTNNPgUG96T0jXBqa5A401HLJpWJpEmjtURORlvOVZ82vVbtdmZAT9PmMoeM32hk6XjGBj7oyWAyey3k5BYvnqPVtAZTpuJlHWf8S1dqDZyEphqd09s6QJBSJS5lf9NwTn6ZwzkPQgpjTSo4gGYX+HiYEi7CSiocIPHZ9OEmA3PG2PrJLNAzDN18P6kKqkcYzDxhIFDLHQa6U8pVsXbQ9osWNt3HJMZCjhQPNbJp0nuM7ahg3bF0B9IRUyoCk+ae/y06S2UV5aTULihH7rS9EKq9CZwh7oTi4vmMMswK9WUr/mVzG9h8K1Gew3o0vB0pclkSLm2N2rgJsmoNgvP+UTKWyeMXJosrBED/BTLYQ6fWSx/Z2ps0w9aybxYauUPgPh4IwIJ69ynvca19zoYy/SLRDbBXTRgAn7GHTUNq07MvlzQYEnT2rEatFzsuyAStugzwPikqJBCuf3PBNq4gUPx/2E6fdOhEr58VQEkVr0qG/RP80Qn2fv/yRgkXoj+Qi6f/c+XiJc3TzIVYbslL5i8='

gateway:
  ip: 172.18.0.5